MessageBus.MessageTypeIsNotMulticast=消息类型 '%s' 不是多播消息
MessageBus.MessageTypeIsNotUnicast=消息类型 '%s' 不是单播消息
MessageBus.MessageTypeIsNotRequest=消息类型 '%s' 不是请求消息
MessageBus.FailedInsertOutboxEntry=消息 '%s' 插入发件箱失败
MessageBus.NoneTransportFound=未找到消息类型 '%s' 的传输通道
MessageBus.MultipleTransportsFound=找到多个消息类型 '%s' 的传输通道
MessageBus.ConfiguratorNotRegistered=未找到配置器服务
MessageBus.CanNotResolveChannelFromMessageType=消息类型 '%s' 未注册且未实现Message接口。请在选项中指定通道名称。

MessageHandlerFinder.MethodMustContainOneParameter=方法 '%s.%s' 必须包含至少一个参数
MessageHandlerFinder.SecondParameterMustBeOfTypeMessageContext=方法 '%s.%s' 的第二个参数必须是 MessageContext 类型
MessageHandlerFinder.ParameterTypeMustImplementMessageInterface=如果未通过 @Subscribe 或 @Channel 指定通道名称，方法 '%s.%s' 的参数类型 '%s' 必须实现 Message 接口

ChannelRegistrar.MessageTypeMismatch=消息类型 '%s' 与通道类型 '%s' 不匹配

DefaultTransportStrategyBuilder.FailedToInstantiateStrategy=无法实例化类型为 '%s' 的策略
DefaultMessageConventionBuilder.FailedToInstantiateConvention=无法实例化类型为 '%s' 的约定

MessageMetadata.ValueOfKeyIsNotTypeOf=键 '%s' 的值不是 '%s' 类型
