MessageBus.MessageTypeIsNotMulticast=The message type '%s' is not a multicast message
MessageBus.MessageTypeIsNotUnicast=The message type '%s' is not a unicast message
MessageBus.MessageTypeIsNotRequest=The message type '%s' is not a request message
MessageBus.FailedInsertOutboxEntry=Failed to insert message '%s' into outbox table
MessageBus.NoneTransportFound=None transport found for message type '%s'
MessageBus.MultipleTransportsFound=Multiple transports found for message type '%s'
MessageBus.ConfiguratorNotRegistered=Configurator service not found
MessageBus.CanNotResolveChannelFromMessageType=The message type '%s' is not registered and does not implement the Message interface. Please specify a channel name in the options.

MessageHandlerFinder.MethodMustContainOneParameter=The method '%s.%s' must contain one parameter
MessageHandlerFinder.SecondParameterMustBeOfTypeMessageContext=The second parameter of method '%s.%s' must be of type MessageContext
MessageHandlerFinder.ParameterTypeMustImplementMessageInterface=If the channel name is not specified by @Subscribe or @Channel, the parameter type '%s' of method '%s.%s' must implement the Message interface

ChannelRegistrar.MessageTypeMismatch=The message type '%s' does not match the channel type '%s'

DefaultTransportStrategyBuilder.FailedToInstantiateStrategy=Failed to instantiate strategy of type '%s'
DefaultMessageConventionBuilder.FailedToInstantiateConvention=Failed to instantiate convention of type '%s'

MessageMetadata.ValueOfKeyIsNotTypeOf=Value of key '%s' is not of type '%s'
