MessageBus.MessageTypeIsNotMulticast=消息類型 '%s' 不是多播消息
MessageBus.MessageTypeIsNotUnicast=消息類型 '%s' 不是單播消息
MessageBus.MessageTypeIsNotRequest=消息類型 '%s' 不是請求消息
MessageBus.FailedInsertOutboxEntry=消息 '%s' 插入寄件匣失敗
MessageBus.NoneTransportFound=未找到消息類型 '%s' 的傳輸通道
MessageBus.MultipleTransportsFound=找到多個消息類型 '%s' 的傳輸通道
MessageBus.ConfiguratorNotRegistered=未找到配置器服務
MessageBus.CanNotResolveChannelFromMessageType=消息類型 '%s' 未註冊且未實作Message介面。請在選項中指定通道名稱。

MessageHandlerFinder.MethodMustContainOneParameter=方法 '%s.%s' 必須包含至少一個參數
MessageHandlerFinder.SecondParameterMustBeOfTypeMessageContext=方法 '%s.%s' 的第二個參數必須是 MessageContext 類型
MessageHandlerFinder.ParameterTypeMustImplementMessageInterface=如果未透過 @Subscribe 或 @Channel 指定通道名稱，方法 '%s.%s' 的參數類型 '%s' 必須實作 Message 介面

ChannelRegistrar.MessageTypeMismatch=消息類型 '%s' 與通道類型 '%s' 不匹配

DefaultTransportStrategyBuilder.FailedToInstantiateStrategy=無法實例化類型為 '%s' 的策略
DefaultMessageConventionBuilder.FailedToInstantiateConvention=無法實例化類型為 '%s' 的約定
