MessageTransportNotFoundException.Message=消息传输通道 '%s' 未找到
ChannelNotRegisterException.Message=消息通道 '%s' 未注册。
MessageDeliverException.Message=消息传递过程中发生错误。

MessageMetadata.ValueOfKeyIsNotTypeOf=键 '%s' 的值不是 '%s' 类型

DeadLetterMessage.ReasonUnknown=未知
