MessageTransportNotFoundException.Message=訊息傳輸通道 '%s' 未找到
ChannelNotRegisterException.Message=訊息通道 '%s' 未註冊。
MessageDeliverException.Message=訊息傳遞過程中發生錯誤。

MessageMetadata.ValueOfKeyIsNotTypeOf=鍵 '%s' 的值不是 '%s' 類型

DeadLetterMessage.ReasonUnknown=未知
