MessageTransportNotFoundException.Message=Message transport %s not found
ChannelNotRegisterException.Message=Message channel '%s' is not registered.
MessageDeliverException.Message=Error occurred during message deliver.

MessageMetadata.ValueOfKeyIsNotTypeOf=The value of key '%s' is not of type '%s'
