RuleCheckException.Message=对象不符合保存要求。

ObjectReflector.CriteriaRequired=当参数数量大于 0 时，条件不能为空。

PropertyInfoList.ThreadInterruptedException=获取信号量时线程被中断。

FieldDataManager.PropertyNotRegistered=属性 '%s' 未注册。

BusinessObjectFactory.UnexpectedState=保存类型为 '%2$s' 的业务对象时遇到意外的状态 '%1$s'。
BusinessObjectFactory.CannotSaveReadOnly=无法保存类型为 '%s' 的只读业务对象。
BusinessObjectFactory.NoConstructor=未找到类型为 '%s' 的业务对象的构造函数。
BusinessObjectFactory.CreateInstanceFailed=创建类型为 '%s' 的业务对象实例失败。
BusinessObjectFactory.InvokeMethodFailed=无法在类型为 '%2$s' 的目标对象上调用方法 '%1$s'。

BusinessContext.InstanceCreationNotSupported=BusinessContext 不支持实例创建。

BusinessObject.PropertyNotReadable=类型为 '%2$s' 的业务对象的属性 '%1$s' 不可读。
BusinessObject.PropertyNotWritable=类型为 '%2$s' 的业务对象的属性 '%1$s' 不可写。

RequiredRule.Message=属性 '%s' 的值不能为空。
