RuleCheckException.Message=物件不符合儲存要求。

ObjectReflector.CriteriaRequired=當參數數量大於 0 時，條件不能為空。

PropertyInfoList.ThreadInterruptedException=獲取信號量時執行緒被中斷。

FieldDataManager.PropertyNotRegistered=屬性 '%s' 未註冊。

BusinessObjectFactory.UnexpectedState=儲存類型為 '%2$s' 的業務物件時遇到意外的狀態 '%1$s'。
BusinessObjectFactory.CannotSaveReadOnly=無法儲存類型為 '%s' 的唯讀業務物件。
BusinessObjectFactory.NoConstructor=未找到型別為 '%s' 的業務物件的建構函式。
BusinessObjectFactory.CreateInstanceFailed=建立型別為 '%s' 的業務物件執行個體失敗。
BusinessObjectFactory.InvokeMethodFailed=無法在型別為 '%2$s' 的目標物件上呼叫方法 '%1$s'。

BusinessContext.InstanceCreationNotSupported=BusinessContext 不支援執行個體建立。

BusinessObject.PropertyNotReadable=型別為 '%2$s' 的業務物件的屬性 '%1$s' 不可讀。
BusinessObject.PropertyNotWritable=型別為 '%2$s' 的業務物件的屬性 '%1$s' 不可寫。

RequiredRule.Message=屬性 '%s' 的值不能為空。
