RuleCheckException.Message=Object not valid for save.

AmbiguousMethodException.Message=Ambiguous method selection: multiple methods match the criteria.
ObjectReflector.CriteriaRequired=Criteria cannot be null when parameter count is greater than 0.
