RuleCheckException.Message=Object not valid for save.

ObjectReflector.CriteriaRequired=Criteria cannot be null when parameter count is greater than 0.

PropertyInfoList.ThreadInterruptedException=Thread was interrupted while trying to acquire semaphore.

FieldDataManager.PropertyNotRegistered=Property '%s' is not registered.

BusinessObjectFactory.UnexpectedState=Unexpected state '%s' encountered while saving business object of type '%s'.
BusinessObjectFactory.CannotSaveReadOnly=Cannot save read-only business object of type '%s'.
BusinessObjectFactory.NoConstructor=No constructor found for business object of type '%s'.
BusinessObjectFactory.CreateInstanceFailed=Failed to create instance of business object of type '%s'.
BusinessObjectFactory.InvokeMethodFailed=Failed to invoke method '%s' on target of type '%s'.

BusinessContext.InstanceCreationNotSupported=BusinessContext does not support instance creation.

BusinessObject.PropertyNotReadable=Property '%s' of business object type '%s' is not readable.
BusinessObject.PropertyNotWritable=Property '%s' of business object type '%s' is not writable.

RequiredRule.Message=Value cannot be null or empty of property '%s'.
