SnowflakeId.ClockBackwardException=Clock moved backwards. Refusing to generate id for %d milliseconds
SnowflakeId.WorkIdOverflowException=Worker id overflow. The max worker id must between 0 and %d
SnowflakeId.DatacenterIdOverflowException=Datacenter id overflow. The max datacenter id must between 0 and %d
Singleton.FailedToCreateInstanceException=Failed to create singleton instance for class %s

ArgumentNullException.Message1=Argument '%s' cannot be null
ArgumentNullException.Message2=Argument '%s' cannot be null or empty

ArgumentOutOfRangeException.Message.Equals=The argument '%s' cannot be equal to '%s'
ArgumentOutOfRangeException.Message.GreaterThan=The argument '%s' cannot be greater than '%s'
ArgumentOutOfRangeException.Message.GreaterThanOrEqual=The argument '%s' cannot be greater than or equal to '%s'
ArgumentOutOfRangeException.Message.LessThan=The argument '%s' cannot be less than '%s'
ArgumentOutOfRangeException.Message.LessThanOrEqual=The argument '%s' cannot be less than or equal to '%s'
ArgumentOutOfRangeException.Message.NotInRange=The argument '%s' must be between '%s' and '%s'
ArgumentOutOfRangeException.Message.InRange=The argument '%s' must not be between '%s' and '%s'
ArgumentOutOfRangeException.Message.Negative=The argument '%s' cannot be negative
ArgumentOutOfRangeException.Message.NegativeOrZero=The argument '%s' cannot be negative or zero
ArgumentOutOfRangeException.Message.Zero=The argument '%s' cannot be zero
