SnowflakeId.ClockBackwardException=Clock moved backwards. Refusing to generate id for %d milliseconds
SnowflakeId.WorkIdOverflowException=Worker id overflow. The max worker id must between 0 and %d
SnowflakeId.DatacenterIdOverflowException=Datacenter id overflow. The max datacenter id must between 0 and %d
Singleton.FailedToCreateInstanceException=Failed to create singleton instance for class %s
